apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  # namespace: demo-project
  labels:
    app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: kimheang68/demo-api:13
        ports:
        - containerPort: 8080
        resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
      