---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
commonLabels:
  app: demo-api
resources:
- service.yaml
- deployment.yaml
images:
- name: kimheang68/demo-api
  newTag: "13"


# commonLabels:
#   app: demo-api

# resources:
# - deployment.yaml
# - service.yaml
# - configMap.yaml