apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/microservice1

patches:
  - microservice1/deployment.yaml  # Assuming the patch file is named deployment.yaml
