apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/microservice1

patchesJson6902:
   - target:
      version: v1
      kind: Deployment
      name: demo-api
     patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

