apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/microservice1

patches:
  - patch: | # Indicate this is a patch and use a '|' to preserve newlines
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: demo-api
      spec:
        replicas: 3
    target:
      kind: Deployment
      name: demo-api
      namespace: staging